# Self-Organizing Maps - SOM

Som is an artificial neural network designed for unsupervised learning. They are widely used for dimensionality reduction, clustering and visualization.

 * Step 1 : Initialize the weight vectors $w_i$ randomly or based on some heuristic.
 * Step 2 : Randomly select an input vector $x$ from the dataset.
 * Step 3 : Select a winning neuron using a distance metric
 * Step 4 : Update neuron weights
 * Step 5 : Go back to 2 until done training.


**Clustering After Training**: Once SOM is trained, the clustering process begins;
 * Map input data to neurons: For each data point in the data, compute the Best Matching Unit by finding the neuron with the smallest distance to the data point. Assign the data point to the BMU.
 * This effectively groups the input data based on which neuron represents them best.


## Steps for Training a Self-Organizing Map

### 1. **Initialization**

First, initialize the weights of the map. The weights are typically set to small random values. The SOM consists of a 2D grid of neurons, each of which has a weight vector of the same dimensionality as the input data.

Let the weight vector of the $i$-th neuron be $ \mathbf{w_i} \in \mathbb{R}^n $, where $n$ is the dimensionality of the input space. Initially, these weight vectors are set randomly.

$$
\mathbf{w_i}^{(0)} = \text{random values}, \quad i = 1, 2, \dots, N
$$

Where $N$ is the total number of neurons in the map.

### 2. **Input Selection**

At each step in the training process, a random input vector $ \mathbf{x} \in \mathbb{R}^n $ is selected from the training data.

$$
\mathbf{x} = (x_1, x_2, \dots, x_n)
$$

### 3. **Finding the Best Matching Unit (BMU)**

The Best Matching Unit (BMU) is the neuron whose weight vector is most similar to the input vector $ \mathbf{x} $. This is typically calculated using the Euclidean distance.

The BMU, $ \mathbf{w_{BMU}} $, is found by minimizing the distance between the input vector $ \mathbf{x} $ and the weight vectors of the neurons in the map:

$$
BMU = \arg \min_{i} \| \mathbf{x} - \mathbf{w_i} \|
$$

Where:
- $ \mathbf{w_i} $ is the weight vector of the $i$-th neuron.
- $ \| \cdot \| $ represents the Euclidean distance.

### 4. **Updating the Weights**

After identifying the BMU, the weights of the BMU and its neighbors are updated to make them more similar to the input vector. This helps the map "learn" the input data by adjusting the weights to better represent the data distribution.

The weight update rule is as follows:

$$
\mathbf{w_i}(t+1) = \mathbf{w_i}(t) + \eta(t) \cdot h_{i, BMU}(t) \cdot (\mathbf{x} - \mathbf{w_i}(t))
$$

Where:
- $ \mathbf{w_i}(t) $ is the weight vector of the $i$-th neuron at time $t$.
- $ \eta(t) $ is the learning rate at time $t$.
- $ h_{i, BMU}(t) $ is the neighborhood function, which determines the influence of the BMU on the other neurons.
- $ \mathbf{x} $ is the input vector.
- The neighborhood function $ h_{i, BMU}(t) $ is typically a Gaussian function, defined as:

$$
h_{i, BMU}(t) = \exp\left(-\frac{\| i - BMU \|^2}{2\sigma(t)^2}\right)
$$

Where:
- $ \sigma(t) $ is the width of the neighborhood at time $t$.
- $ \| i - BMU \| $ is the distance between the $i$-th neuron and the BMU on the grid.

### 5. **Decay of Learning Rate and Neighborhood Size**

As training progresses, the learning rate $ \eta(t) $ and the neighborhood size $ \sigma(t) $ are decayed over time to ensure that the map converges. The decay functions typically take the following forms:

$$
\eta(t) = \eta_0 \cdot \exp\left(-\frac{t}{\tau_1}\right)
$$
$$
\sigma(t) = \sigma_0 \cdot \exp\left(-\frac{t}{\tau_2}\right)
$$

Where:
- $ \eta_0 $ is the initial learning rate.
- $ \sigma_0 $ is the initial neighborhood size.
- $ \tau_1 $ and $ \tau_2 $ are time constants that control the decay rates.

### 6. **Iteration and Convergence**

The above steps are repeated for a number of iterations or until the map has converged. During each iteration, the weights of the neurons are updated to better represent the data. Over time, the neurons self-organize, with similar input vectors being mapped to nearby neurons.

### 7. **Final Map**

After the training process is complete, the SOM will have organized the neurons in such a way that similar data points are represented by nearby neurons on the map. The map can now be used for visualization, clustering, or other tasks.

## Summary of Equations

1. **Initialization**: Random weight vectors $ \mathbf{w_i} \in \mathbb{R}^n $.
2. **BMU Identification**:
   $$
   BMU = \arg \min_{i} \| \mathbf{x} - \mathbf{w_i} \|
   $$
3. **Weight Update**:
   $$
   \mathbf{w_i}(t+1) = \mathbf{w_i}(t) + \eta(t) \cdot h_{i, BMU}(t) \cdot (\mathbf{x} - \mathbf{w_i}(t))
   $$
4. **Neighborhood Function**:
   $$
   h_{i, BMU}(t) = \exp\left(-\frac{\| i - BMU \|^2}{2\sigma(t)^2}\right)
   $$
5. **Decay Functions**:
   $$
   \eta(t) = \eta_0 \cdot \exp\left(-\frac{t}{\tau_1}\right)
   $$
   $$
   \sigma(t) = \sigma_0 \cdot \exp\left(-\frac{t}{\tau_2}\right)
   $$

## Conclusion

Self-Organizing Maps are powerful tools for clustering and visualizing high-dimensional data. By preserving the topological properties of the input data and using unsupervised learning, SOMs can be a useful technique for a variety of tasks, from exploratory data analysis to pattern recognition.



In [16]:
import torch
# Input vector
x = torch.tensor([1.0, 2.0])
print(' x shape = ',x.shape)
print(' x unsqueeze shape = ',x.unsqueeze(0).shape)

# Weights of neurons
weights = torch.tensor([
    [1.0, 1.0],
    [2.0, 2.0],
    [3.0, 3.0],
    [0.0, 0.0]
])
# Compute pairwise distances
distances = torch.cdist(x.unsqueeze(0), weights).squeeze(0)

print("Distances:", distances)

 x shape =  torch.Size([2])
 x unsqueeze shape =  torch.Size([1, 2])
Distances: tensor([1.0000, 1.0000, 2.2361, 2.2361])


In [21]:
torch.cdist(x.unsqueeze(0), weights).squeeze(0)

tensor([1.0000, 1.0000, 2.2361, 2.2361])

In [23]:
torch.argmin(torch.cdist(x.unsqueeze(0), weights))

tensor(0)

In [70]:
import torch
import torch.nn as nn
import numpy as np

class SOM(nn.Module):
    def __init__(self, m, n, dim, lr=0.1, sigma=None):
        """
        Initialize the Self-Organizing Map (SOM).

        Args:
            m (int): Number of rows in the SOM grid.
            n (int): Number of columns in the SOM grid.
            dim (int): Dimensionality of the input data.
            lr (float): Initial learning rate.
            sigma (float): Initial neighborhood radius. If None, defaults to max(m, n) / 2.
        """
        super(SOM, self).__init__()
        self.m = m
        self.n = n
        self.dim = dim
        self.lr = lr
        self.sigma = sigma if sigma is not None else max(m, n) / 2.0
        self.weights = nn.Parameter(torch.randn(m * n, dim))  # Weight vectors for neurons
        self.locations = torch.tensor([(i, j) for i in range(m) for j in range(n)], dtype=torch.float)  # Neuron grid


    def compute_distances(self, x):
        """
        Compute distances between the input vector and all neuron weights.

        Args:
            x (torch.Tensor): Input data of shape (dim,).

        Returns:
            torch.Tensor: Distances of shape (m * n,).
        """
        return torch.cdist(x.unsqueeze(0), self.weights).squeeze(0)

    def find_bmu(self, x):
        """
        Find the Best Matching Unit (BMU) for the input vector.

        Args:
            x (torch.Tensor): Input data of shape (dim,).

        Returns:
            int: Index of the BMU.
        """
        dists = self.compute_distances(x)
        bmu_idx = torch.argmin(dists)
        return bmu_idx

    def compute_neighborhood_function(self, bmu_idx, t, max_iter):
        """
        Compute the neighborhood function for all neurons.

        Args:
            bmu_idx (int): Index of the BMU.
            t (int): Current iteration.
            max_iter (int): Total number of iterations.

        Returns:
            torch.Tensor: Neighborhood function values of shape (m * n,).
        """
        bmu_loc = self.locations[bmu_idx]
        sigma_t = self.sigma * (1 - t / max_iter)
        dists = torch.cdist(bmu_loc.unsqueeze(0), self.locations.unsqueeze(0)).squeeze(0)
        return torch.exp(-dists**2 / (2 * sigma_t**2))

    def update_weights(self, x, h, lr_t):
        """
        Update the SOM weights using the input vector and neighborhood function.

        Args:
            x (torch.Tensor): Input data of shape (dim,).
            h (torch.Tensor): Neighborhood function values of shape (m * n,).
            lr_t (float): Learning rate for the current iteration.
        """
        delta = torch.matmul(lr_t * h ,(x - self.weights))
        self.weights.data += delta

    def train_step(self, x, t, max_iter):
        """
        Perform a single training step for the SOM.

        Args:
            x (torch.Tensor): Input data of shape (dim,).
            t (int): Current iteration.
            max_iter (int): Total number of iterations.
        """
        lr_t = self.lr * (1 - t / max_iter)
        bmu_idx = self.find_bmu(x)
        h = self.compute_neighborhood_function(bmu_idx, t, max_iter)
        self.update_weights(x, h, lr_t)

    def fit(self, data, max_iter=1000):
        for t in range(max_iter):
            print(f'iteration : {t}')
            for x in data:
                self.train_step(x, t, max_iter)


    def map_data(self, data):
        mapped_data = []
        for x in data:
            bmu_idx = self.find_bmu(x)
            mapped_data.append(self.locations[bmu_idx].numpy())
        return np.array(mapped_data)

In [ ]:
m, n = 3, 4 # SOM grid size
dim = 3        # Input vector dimensionality
lr = 0.1       # Learning rate
sigma = None   # Neighborhood radius
max_iter = 1000
data = torch.rand(100, dim)
som = SOM(m, n, dim, lr, sigma)
som.fit(data)

In [72]:
print("SOM training complete.")
print("Trained weights:", som.weights)

SOM training complete.
Trained weights: Parameter containing:
tensor([[-6.0190e-01,  2.3437e+00,  4.2188e-01],
        [-9.3998e-01,  1.7042e+00,  1.7636e+00],
        [ 1.6531e+00,  1.1579e+00, -6.0795e-01],
        [-1.3678e-01, -6.0188e-01,  8.0042e-01],
        [ 1.0580e+00,  1.6371e+00,  9.4964e-01],
        [-1.0015e+00,  1.5702e+00,  2.4568e+00],
        [ 2.6441e+00,  1.7342e+00, -5.6422e-03],
        [ 4.0110e-02,  2.0327e+00,  7.0524e-04],
        [ 1.1131e+00,  4.9359e-01,  2.6526e-01],
        [ 2.6269e-01,  4.2324e-01,  5.1039e-01],
        [ 1.5281e+00, -2.8601e-03,  8.6815e-01],
        [-7.1944e-01, -8.8627e-01,  1.5111e+00]], requires_grad=True)


In [29]:
som.locations

tensor([[0., 0.],
        [0., 1.],
        [0., 2.],
        [0., 3.],
        [1., 0.],
        [1., 1.],
        [1., 2.],
        [1., 3.],
        [2., 0.],
        [2., 1.],
        [2., 2.],
        [2., 3.]])

In [32]:
som.sigma,som.lr,som.m,som.n

(2.0, 0.1, 3, 4)

In [33]:
som.weights

Parameter containing:
tensor([[ 1.2405,  0.0368, -0.1742],
        [-0.4640, -1.2445, -0.3456],
        [ 0.6999,  0.7625,  0.9033],
        [ 0.7039,  0.2620,  1.0712],
        [-0.3758,  1.0875, -1.6021],
        [-0.2572,  1.1723, -0.6717],
        [ 0.1132,  1.9317, -0.0093],
        [-0.2807,  0.4744, -0.5122],
        [-1.5433, -0.6124, -0.3056],
        [ 1.2074, -0.0209, -0.2505],
        [ 1.5048,  1.7877, -1.0763],
        [-1.0436,  0.2622,  0.1690]], requires_grad=True)

In [37]:
x = torch.tensor([0.2,1.7,0.9])
bmu_idx = som.find_bmu(x)
bmu_idx

tensor(6)

In [40]:
bmu_loc = som.locations[bmu_idx]
bmu_loc

tensor([1., 2.])

In [41]:
t = 1
max_iter = 10
sigma_t = som.sigma * (1 - t / max_iter)
sigma_t

1.8

In [45]:
som.locations.unsqueeze(0)

tensor([[[0., 0.],
         [0., 1.],
         [0., 2.],
         [0., 3.],
         [1., 0.],
         [1., 1.],
         [1., 2.],
         [1., 3.],
         [2., 0.],
         [2., 1.],
         [2., 2.],
         [2., 3.]]])

In [42]:
dists = torch.cdist(bmu_loc.unsqueeze(0), som.locations.unsqueeze(0)).squeeze(0)

In [43]:
dists

tensor([[2.2361, 1.4142, 1.0000, 1.4142, 2.0000, 1.0000, 0.0000, 1.0000, 2.2361,
         1.4142, 1.0000, 1.4142]])

In [50]:
h = torch.exp(-dists**2 / (2 * sigma_t**2))
print(h.shape)
h

torch.Size([1, 12])


tensor([[0.4623, 0.7344, 0.8570, 0.7344, 0.5394, 0.8570, 1.0000, 0.8570, 0.4623,
         0.7344, 0.8570, 0.7344]])

In [49]:
h.unsqueeze(1).shape

torch.Size([1, 1, 12])

In [62]:
lr_t = 0.3
a = h*lr_t
b = (x-som.weights)
print(a.shape)
print(b.shape)
delta = torch.matmul(a, b)
delta

torch.Size([1, 12])
torch.Size([12, 3])


tensor([[0.0811, 2.9118, 2.9195]], grad_fn=<MmBackward0>)

In [63]:
som.weights+delta

tensor([[ 1.3217,  2.9486,  2.7453],
        [-0.3828,  1.6673,  2.5740],
        [ 0.7811,  3.6743,  3.8229],
        [ 0.7850,  3.1737,  3.9907],
        [-0.2947,  3.9993,  1.3174],
        [-0.1760,  4.0841,  2.2479],
        [ 0.1943,  4.8434,  2.9103],
        [-0.1996,  3.3862,  2.4073],
        [-1.4622,  2.2994,  2.6139],
        [ 1.2886,  2.8909,  2.6690],
        [ 1.5860,  4.6995,  1.8432],
        [-0.9625,  3.1739,  3.0886]], grad_fn=<AddBackward0>)

In [75]:
import torch
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.datasets import make_blobs

# Generate synthetic 100-dimensional data (replace this with your actual data)
X, _ = make_blobs(n_samples=1000, n_features=100, centers=5)

# Initialize the SOM with a 10x10 grid, 100 input dimensions, and a learning rate
som = SOM(m=10, n=10, dim=100, lr=0.1, sigma=1.0)

# Convert the dataset to a tensor
X_tensor = torch.tensor(X, dtype=torch.float32)

# Train the SOM
som.fit(X_tensor,100)

# Map the data to the SOM grid (get the 2D positions for each point)
mapped_data = som.map_data(X_tensor)

iteration : 0
iteration : 1
iteration : 2
iteration : 3
iteration : 4
iteration : 5
iteration : 6
iteration : 7
iteration : 8
iteration : 9
iteration : 10
iteration : 11
iteration : 12
iteration : 13
iteration : 14
iteration : 15
iteration : 16
iteration : 17
iteration : 18
iteration : 19
iteration : 20
iteration : 21
iteration : 22
iteration : 23
iteration : 24
iteration : 25
iteration : 26
iteration : 27
iteration : 28
iteration : 29
iteration : 30
iteration : 31
iteration : 32
iteration : 33
iteration : 34
iteration : 35
iteration : 36
iteration : 37
iteration : 38
iteration : 39
iteration : 40
iteration : 41
iteration : 42
iteration : 43
iteration : 44
iteration : 45
iteration : 46
iteration : 47
iteration : 48
iteration : 49
iteration : 50
iteration : 51
iteration : 52
iteration : 53
iteration : 54
iteration : 55
iteration : 56
iteration : 57
iteration : 58
iteration : 59
iteration : 60
iteration : 61
iteration : 62
iteration : 63
iteration : 64
iteration : 65
iteration : 66
itera

In [76]:
mapped_data.shape

(1000, 2)

In [77]:
mapped_data

array([[6., 7.],
       [4., 6.],
       [6., 7.],
       ...,
       [8., 6.],
       [2., 4.],
       [2., 4.]], dtype=float32)